server:
  port: 8888
  servlet:
    context-path: /baidu
logging:
  level:
    root: error
    com.yc: info
    org.springframework: error
  file:
    path: ./logs
    name: yc.log

yc:
  tname: zy
  age: 20